# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Dev

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
      
steps:

- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

#Install Python packagers
- script: |
     pip install wheel
     pip install twine
  displayName: 'Install python packagers'

#Build Package DadJokes
- script: |
     cd microservices
     python DadJokes/setup.py bdist_wheel
  displayName: "Build DadJokes Artifact"
  
#Build Package Kanye
- script: |
     cd microservices
     python Kanye/setup.py bdist_wheel
  displayName: 'Build Kanye Artifact'
  
#Upload python packages
- task: TwineAuthenticate@1
  displayName: Twine Authenticate
  inputs:
    artifactFeed: 'python_feed'       
    
- script: |
     cd microservices
     python -m twine upload -r 'python_feed' --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Upload python Artifacts'

#Build Package MyJokes
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd microservices/MyJokes
    npm install
    npm run build
  displayName: 'npm build'
  
#upload MyJokes Packages
- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: 'nodejs_feed'