# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Dev

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
      
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    cd microservices/DadJokes
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
  
- script: |
    pip install twine
    pip install build

- script: |
    cd microservices/DadJokes
    python -m build -w

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'python_feed'

- script: |
    cd microservices/DadJokes
    python -m twine upload -r azure-devops-project --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'upload'